<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.0" />
    <PackageReference Include="Marten" Version="8.14.0" />
    <PackageReference Include="WolverineFx" Version="5.1.0" />
    <PackageReference Include="WolverineFx.Http" Version="5.1.0" />
    <PackageReference Include="WolverineFx.Marten" Version="5.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Handlers\Members\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\borrowing\Message.Borrowing\Messages.Borrowing.csproj" />
    <ProjectReference Include="..\..\report\Messages.Report\Messages.Report.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
