<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3458f136-ffc0-493d-95b5-3b60e097a413</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" Version="8.14.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.6" />
    <PackageReference Include="WolverineFx" Version="5.0.0" />
    <PackageReference Include="WolverineFx.Marten" Version="5.0.0" />
    <PackageReference Include="WolverineFx.Postgresql" Version="5.0.0" />
    <PackageReference Include="WolverineFx.RabbitMQ" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\services\catalogService\catalogService.Application\Application.csproj" />
    <ProjectReference Include="..\services\catalogService\catalogService.Infranstructure\Infranstructure.csproj" />
  </ItemGroup>

</Project>
